name: Azure Web App CI/CD

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-app-name'      # Replace with your Azure Web App name
        slot-name: 'production'        # Replace with your deployment slot, e.g., 'staging' or 'production'
        package: '.'                   # Specify the directory/package to deploy
